Banner rotation
usmartpro/banner-rotation pull request #1
Opened 2022-04-28 17:38 UTC by usmartpro

Первая итерация проекта.
Пока отсутствуют интеграционные тесты, добавлю попозже )

2022-04-30 07:21 UTC, kulti requested changes
Артур, спасибо за проект.

Почти все уже готово. Не забудьте про обязательные требования. Особенно жду в финальной интеграционных тестов и docker-compose файлов, чтобы поднять окружение и потыкать живой проект.

2022-04-30 07:21 UTC, kulti commented on README.md
> +#Архитектура
Хорошо, что есть ридми. Осталось немного с маркдауном разобраться. Сверху, рядом с галочкой Viewed есть три точки, можно выбрать пункт View File и посмотреть, как он выглядит. Есть что допилить :)

2022-04-30 07:21 UTC, kulti commented on build/app/Dockerfile
> +COPY .. ${CODE_DIR}
Тут точно `..`, а не `.`? Выглядит очень странно и нелогично.

2022-04-30 07:21 UTC, kulti commented on cmd/banner/main.go
> +	internalstorage "github.com/usmartpro/banner-rotation/internal/storage"
А зачем пакеты перемименовывать? Чем не устраивают имена app, config и прочие? С mq почему-то не стали так делать. Как минимум, неконсистентно.

2022-04-30 07:21 UTC, kulti commented on cmd/banner/main.go
> +	<-ctx.Done()
Тут программа выйдет сразу, не будет попытки остановить сервер. Зачем вообще нужна горутина на 64 строке? Может, без нее можно обойтись.

2022-04-30 07:21 UTC, kulti commented on internal/server/http/handlers.go
> +	w.Header().Add("Content-Type", "application/json")
Странно ставить этот заголовок, ведь у респонза нет боди/контента.

2022-04-30 07:21 UTC, kulti commented on internal/server/http/handlers.go
> +	if err = json.NewDecoder(r.Body).Decode(&bS); err != nil {
Зачем отдельно заводить переменную err? Обычно пишут так `if err =: json.NewDecoder(r.Body).Decode(&bS); err != nil {`. Суть в том, чтобы у переменной была максимально узкая область видимости.

2022-04-30 07:21 UTC, kulti commented on internal/server/http/handlers.go
> +	responseData, _ := json.Marshal(result)
Не игнорируйте ошибки, даже если они кажутся вам невероятными. Что-то потом в другой части программы поменяют и она станет вполне реальной, а вы об этом не узнаете.

2022-04-30 07:21 UTC, kulti commented on internal/server/http/middleware.go
> +		writer := &ResponseWriter{w, 0, 0}
Здесь есть интересный момент. Оригинальный ResponseWriter может реализовывать (и обычно реализует) дополнительные интерфейсы. Текущий подход скроет их. Вот так можно создавать более корректную обертку — https://gist.github.com/kulti/79ad30738aa2e6f5f1bfb13cb4522c5a

2022-04-30 07:21 UTC, kulti commented on internal/mq/rabbit.go
> +func (q *Rabbit) GetChannel() *amqp.Channel {
Не понимаю, зачем этот метод. Использования не нашел. Выглядит опасным.

2022-04-30 07:21 UTC, kulti commented on internal/mq/rabbit.go
> +func (q *Rabbit) GetNotificationChannel() (<-chan app.StatEvent, error) {
Это тоже пока не используется. Возможно, заготовка для интеграционных тестов. Тогда немного странно, что тут бизнес-логика есть (разбирается конкретная структура данных). Если да тестов, то стоит возвращать сырые данные, которые уже в тестах будут анализироваться. Так честнее будет.

2022-04-30 07:21 UTC, kulti commented on internal/app/multi_armed_bandit_test.go
> +		BannerID, _ = MultiArmedBandit(bannerStats)
Не игнорируйте ошибки. Я серьезно. Это самый простой способ отстрелить себе ногу.

2022-04-30 07:21 UTC, kulti commented on internal/app/multi_armed_bandit_test.go
> +	require.NotPanics(t, func() {
Это странная проверка. MultiArmedBandit не говорит, что паниковать — это один из вариантов его поведения. Если это из общих соображений сделано, то тогда у нас все тесты были бы в подобных инструкциях, что, согласитесь, совершенно неудобно.

2022-04-30 07:21 UTC, kulti commented on internal/app/multi_armed_bandit_test.go
> +		{1, 1, 1, 10, 0},
Это невозможно понять. Тесты такой же код, как и остальное. Рекомендую тут явно все поля указать.

2022-04-30 07:21 UTC, kulti commented on internal/app/multi_armed_bandit.go
> +	// Перебор всех: после большого количества показов, каждый баннер должен быть показан хотя один раз
Думаю, что это лишнее. После показа одного из «одинаковых» баннеров, количество его показов изменится и они перестанут быть «одинаковыми».

2022-04-30 07:21 UTC, kulti commented on internal/app/multi_armed_bandit.go
> +	// момент номер 2: линтер заставил использовать crypto/rand вместо math/rand, пришлось городить конвертации )
Линтер вас не заставляет ничего делать. Он лишь советует. Как и я в дискашенах к этому ПР. Важно понять, почему он это советует. Тогда будет очевидно, что здесь нормально использовать math/rand и можно написать noint — https://golangci-lint.run/usage/false-positives/

2022-04-30 07:21 UTC, kulti commented on internal/app/app.go
> +		bannerID, err = a.Storage.GetRandomBanner(slotID)
Интересная мысль! 👍

Тут есть три момента
1. Вызывается метод стораджа после того, как упал другой метод сторадж. Скорее всего, второй тоже упадет. Поэтому это имеет мало смысла.
2. Больше имело бы смысл этот вызов делать после ошибки в MultiArmedBandit.
3. MultiArmedBandit возвращает ошибку только если его вызовут с пустым набором баннеров. Можно на уровне контракта это запретить и паниковать в MultiArmedBandit. А здесь проверять, что GetBannersInfo вернул больше одного баннера. Тогда все упроститься.

2022-04-30 07:21 UTC, kulti commented on internal/app/app.go
> +	if bannerID == 0 {
Вы уверены, что bannerID не может быть 0? bannerID приходит от пользователя, там что угодно может быть.

2022-04-30 07:21 UTC, kulti commented on migrations/001_create_banners_table.sql
> +CREATE TABLE IF NOT EXISTS banners
IF NOT EXISTS не имеют смысла в миграциях, т.к. они один раз выполняются.

2022-04-30 07:21 UTC, kulti commented on migrations/007_fill_tables_data.sql
> +       (3, 'Пожилые');
Обычно в миграциях не заливают данные, т.к. это не структура БД.

Социальные группы еще, возможно, нормально. Их можно считать частью структуры БД, необходимой для бизнес-логики. Остальное явно лишнее — это уже пресеты данных, которые нужны на каком-нибудь тестовом окружении. Их заливают другими способами, не миграциями.

2022-04-30 07:21 UTC, kulti commented on internal/storage/storage.go
> +			WHERE bs.slot_id = $1 AND (bv.social_group_id = $2 OR bv.social_group_id is null)
Странно, что banner_views может оказаться без social_group_id. Это в принципе имеет мало смысла, мы же знаем кому показываем, как то, кто кликает. Думаю, тут можно проще и на уровне JOIN делать.

2022-04-30 07:21 UTC, kulti commented on Makefile
> +build-img:
Тут вот такая ошибка выдается:
```
~/work/otus-review/usmartpro/banner-rotation > make build-img
docker build \
                --build-arg=LDFLAGS="-X main.release="develop" -X main.buildDate=2022-04-30T07:11:45 -X main.gitHash=8b5b68b" \
                -t "banner-rotation:develop" \
                -f build/Dockerfile .
[+] Building 0.0s (1/2)                                                                                                      
 => [internal] load build definition from Dockerfile                                                                    0.0s
 => => transferring dockerfile: 2B                                                                                      0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount651082123/Dockerfile: no such file or directory
make: *** [build-img] Error 1
```

2022-04-30 07:21 UTC, kulti commented on Makefile
> +	docker run $(DOCKER_IMG)
`docker run --rm -it $(DOCKER_IMG)` — рекомендую хотя бы так сделать.

2022-05-11 09:21 UTC, merged

2022-05-15 10:32 UTC, usmartpro commented on README.md
> +#Архитектура
Поправил кое-какие моменты

2022-05-15 10:32 UTC, usmartpro commented on build/app/Dockerfile
> +COPY .. ${CODE_DIR}
да, исправил

2022-05-15 10:38 UTC, usmartpro commented on cmd/banner/main.go
> +	internalstorage "github.com/usmartpro/banner-rotation/internal/storage"
Убрал все переименования кроме internalhttp. Если его не переименовать, то конфликтует с пакетом net/http. В некоторых местах проекта еще есть переименование internal/storage в sqlstorage. Оставил, так как часто использую storage в наименовании переменных

2022-05-15 10:39 UTC, usmartpro commented on internal/server/http/handlers.go
> +	w.Header().Add("Content-Type", "application/json")
Да, изначально что-то возвращал, забыл убрать. Исправил

2022-05-15 10:47 UTC, usmartpro commented on migrations/001_create_banners_table.sql
> +CREATE TABLE IF NOT EXISTS banners
Тут исходил из предыдущего опыта и требований на текущем месте работы))
Смысл в том, что при выкатке релиза иногда случаются проблемы с составными миграциями (например, несколько последовательных запросов на редактирование структур таблиц) и иногда приходится перенакатывать при некорректных первоначальных запусках. В идеале такого не должно происходить и миграции не должны прописываться как выполненные и в случае чего откатываться. Но на практике случается такое, что некоторые таблицы/колонки/и_прочее могут быть уже созданы и чтобы составные миграции полностью отрабатывали при повторных попытках накатывания и не валились на уже созданных таблицах, которые снова пытаются создаться, то есть требование делать так ))
Понимаю, что: 1) это не совсем корректно 2) возможно с Go таких проблем не возникает, но мне кажется лучше перебздеть и учесть, чем иметь горящие проблемы при релизе. ИМХО.
Буду рад, если вы разнесете мои доводы в пух и прах )) @kulti

2022-05-15 10:48 UTC, usmartpro commented on migrations/007_fill_tables_data.sql
> +       (3, 'Пожилые');
Понял, принял. Спасибо за уточнение

2022-05-15 10:49 UTC, usmartpro commented on Makefile
> +build-img:
Убрал build-img. Не планировал оставлять его.

2022-05-15 10:49 UTC, usmartpro commented on Makefile
> +	docker run $(DOCKER_IMG)
Поправил

2022-05-15 10:50 UTC, usmartpro commented on internal/server/http/handlers.go
> +	if err = json.NewDecoder(r.Body).Decode(&bS); err != nil {
Исправил

2022-05-15 10:51 UTC, usmartpro commented on internal/server/http/handlers.go
> +	responseData, _ := json.Marshal(result)
Исправил. В остальных частях проекта тоже правил по ходу. Но похоже не везде успел до отправки на проверку

2022-05-15 10:51 UTC, usmartpro commented on internal/mq/rabbit.go
> +func (q *Rabbit) GetChannel() *amqp.Channel {
Копипаст из предыдущего проекта )) Убрал

2022-05-15 10:52 UTC, usmartpro commented on internal/mq/rabbit.go
> +func (q *Rabbit) GetNotificationChannel() (<-chan app.StatEvent, error) {
Копипаст из предыдущего проекта )) Убрал

2022-05-15 10:53 UTC, usmartpro commented on internal/app/multi_armed_bandit_test.go
> +		BannerID, _ = MultiArmedBandit(bannerStats)
Исправил

2022-05-15 10:54 UTC, usmartpro commented on internal/app/multi_armed_bandit_test.go
> +	require.NotPanics(t, func() {
Да, в ранней версии MultiArmedBandit он умел паниковать. В процессе написания убрал )
Тут тоже убрал

2022-05-15 10:54 UTC, usmartpro commented on internal/app/multi_armed_bandit_test.go
> +		{1, 1, 1, 10, 0},
Да, прописал

2022-05-15 10:56 UTC, usmartpro commented on internal/app/multi_armed_bandit.go
> +	// момент номер 2: линтер заставил использовать crypto/rand вместо math/rand, пришлось городить конвертации )
понял) переделал на math/rand

2022-05-15 10:57 UTC, usmartpro commented on internal/app/app.go
> +		bannerID, err = a.Storage.GetRandomBanner(slotID)
Резонно. К сожалению долго провозился с интеграционными тестами и банально не успел переделать этот момент (

2022-05-15 11:02 UTC, usmartpro commented on internal/app/app.go
> +	if bannerID == 0 {
В данном случае уверен, так как выше можем получать значение этой переменной либо в MultiArmedBandit, либо в GetRandomBanner. В обоих этих функциях получаем int. 
В целом весь проект рассчитан на int. И все методы и поля в таблицах. То есть на других типах проект не будет работать и методы апи будут возвращать ошибку, так как в структурах, в которых мы считываем данные из методов прописан Int

2022-05-15 11:22 UTC, usmartpro commented on internal/storage/storage.go
> +			WHERE bs.slot_id = $1 AND (bv.social_group_id = $2 OR bv.social_group_id is null)
Тут скорее особенность реализации алгоритма. Сделал так потому, что хочу получить все записи из banner_slot, даже если у баннера нет ни одного просмотра и клика для нашей социальной группы. Если не делать проверку  OR bv.social_group_id is null, то такие баннеры не вернутся в результате и для них не будет рассчитан "доход" (хоть и нулевой) и такой баннер не сможет попасть в выдачу. Кстати, это актуально для первоначальной выдачи, когда ни для одного из баннеров еще нет просмотров и кликов.

2022-05-15 11:23 UTC, usmartpro commented on cmd/banner/main.go
> +	<-ctx.Done()
К сожалению не добрался до этого до дедлайна (

2022-05-15 11:26 UTC, usmartpro commented on internal/server/http/middleware.go
> +		writer := &ResponseWriter{w, 0, 0}
Да, взял на заметку, спасибо. К сожалению тоже до дедлайна не добрался до правки мидлвара (

2022-05-15 11:51 UTC, usmartpro commented
Добрый день, Алексей.
Спасибо за ваши замечания и уделенное время!
Хоть и поздно, но все же добавил кое-какие комментарии.

2022-05-22 08:41 UTC, kulti commented on migrations/001_create_banners_table.sql
> +CREATE TABLE IF NOT EXISTS banners
Один шаг миграции обычно внутри одной транзакции делают. Тогда никакого частичного накатывания миграции быть не может.

Какие-то миграторы автоматически делают шаги в транзакция, в каких-то нужно писать BEGIN+END. Как это в goose устроено не знаю.

2022-05-22 08:45 UTC, kulti commented on internal/app/app.go
> +	if bannerID == 0 {
Ничего не понял :) Тут речь была о том, что в этом месте кода 0 считается некорректным значением. Но это значение полностью контролировалось пользователем, т.е. он мог спокойно 0 в качестве bannerID при создании использовать.

2022-05-22 08:48 UTC, kulti commented on internal/storage/storage.go
> +			WHERE bs.slot_id = $1 AND (bv.social_group_id = $2 OR bv.social_group_id is null)
Ага, понял мысль 👍 Думаю, тут все корректно тогда.